# Generated by Django 3.0.8 on 2020-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=10),
        ),
    ]
